# PyTorch

* Developed at Facebook AI in 2016
* Preferable to quickly prototype, and by researchers
* More Pythonic, and easy to tinker with low level details than Tensorflow, according to most users
* [Building the Same Model with PyTorch & TensorFlow](https://www.youtube.com/watch?v=ay1E1f8VqP8)
* [Crash Course Notebook](https://colab.research.google.com/drive/1eiUBpmQ4m7Lbxqi2xth1jBaL61XTKdxp?usp=sharing)

### Components

In [0]:
from torch import nn

* Every model created in Pytorch inherits from `pytorch.nn` called `nn.module`
* We define the inputs and outputs of the model along with the definitions of the layers of the network within this class

In [0]:
class SimpleNeuralNet(nn.Module):
    ...

* Every Pytorch inherited neural net needs to implement the `__init__` method and `forward` method.
* The `__init__` can define the layers of the model, and `forward` defines how data is passed from one layer to the next. 
> `__init__` is like the static declaration, while `forward` is like `main()` or where execution comes forth across the static components

In [0]:
class SimpleNeuralNet(nn.Module):
    def __init__(self):
        super().__init__()
    
    def forward(self, x):
        ...

Declare a GPU torch device and pass the model object to the GPU

In [0]:
import torch

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(device)

cuda


In [0]:
simple_neural_net_model = SimpleNeuralNet().to(device=device)

### Tensors

In [0]:
t = torch.Tensor([1,2,3])
print(t.shape)
print(t.shape == t.size())
t

torch.Size([3])
True


tensor([1., 2., 3.])

In [0]:
torch.argmax(t)

tensor(2)

In [0]:
t2 = torch.Tensor([[1, 2, 3], [1, 2, 4], [2, 5, 7]])
print(t2.shape)
t2

torch.Size([3, 3])


tensor([[1., 2., 3.],
        [1., 2., 4.],
        [2., 5., 7.]])

In [0]:
# Note different method of getting argmax
t2.argmax()

tensor(8)

When you call `t2.argmax()`, it treats the tensor as if it's a flat array (because no dimension is specified) and returns the index of the maximum value in this flat array. 

In [0]:
t2.argmax(dim=0)

tensor([2, 2, 2])

In [0]:
print(torch.empty(3, 3, 3))

tensor([[[ 1.4165e-31,  4.5904e-41,  2.6298e-16],
         [ 3.0838e-41,  1.5414e-44,  0.0000e+00],
         [ 2.6087e-16,  3.0838e-41,  2.2161e-16]],

        [[ 3.0838e-41,  4.2039e-45,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,         nan],
         [        nan, -1.0326e+15,  4.5902e-41]],

        [[ 0.0000e+00,  4.5904e-41,  1.3565e-42],
         [ 0.0000e+00,  7.0065e-45,  0.0000e+00],
         [ 2.6087e-16,  3.0838e-41,  2.2161e-16]]])


In [0]:
print(torch.rand(3, 3, 3))

tensor([[[0.8454, 0.2887, 0.4848],
         [0.9340, 0.7250, 0.1804],
         [0.2271, 0.1709, 0.4196]],

        [[0.1896, 0.2917, 0.7042],
         [0.5166, 0.3489, 0.2211],
         [0.5743, 0.7340, 0.5540]],

        [[0.4630, 0.8700, 0.8625],
         [0.0443, 0.8961, 0.4219],
         [0.6832, 0.0181, 0.4393]]])


In [0]:
print(torch.zeros(3, 3, 3))

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])


In [0]:
print(torch.ones(3, 3, 3))

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])
